# 业务日志
busi_log_path = "/data/logs/uc.jiange.http/busi_jiange.log"
# 访问日志
access_log_path = "/data/logs/uc.jiange.http/acc_jiange.log"
# 私钥
jd_secret_key = "2s1w6KQZ6VzkxtkdU7j3xEa7SndDKfE9"
# 京东appid
jd_app_id = "c000ed62"
# 拼多多
pdd_app_id = "23e6da55"
pdd_channel_id = "104540"
tmall_channel_id = "104543"

# 启动配置
[server]
  ip = "0.0.0.0"
  port = 20000

# redis配置
[redis]
  address = "192.168.7.185:6015"
  MaxIdle = 8
  MaxActive = 10
  IdleTimeout = 240
